repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/hhatto/autopep8
    rev: "v2.0.4"
    hooks:
      - id: autopep8

#  - repo: https://github.com/pycqa/flake8
#    rev: 6.1.0
#    hooks:
#      - id: flake8
#        description: Command-line utility for enforcing style consistency across Python projects.
#        entry: flake8
#        name: flake8
#        additional_dependencies:
#          [ flake8-eradicate, flake8-bandit, flake8-commas, pep8-naming ]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        description: The uncompromising Python code formatter
        entry: black
        name: black
        args: ["--line-length=79"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        language_version: python3
        types: [ python ]
        require_serial: true
